replicaCount: 1

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: false
  annotations: {}
  name: ""

core:
  image:
    repository: registry.lab.verysmart.house/watchedsky/core
    tag: ""

  service:
    type: ClusterIP
    port: 8888

  resources:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  livenessProbe:
    httpGet:
      path: /livez
      port: http
  readinessProbe:
    httpGet:
      path: /readyz
      port: http

frontend:
  image:
    repository: registry.lab.verysmart.house/watchedsky/frontend
    tag: ""

  service:
    type: ClusterIP
    port: 3000

  resources:
    requests:
      cpu: 100m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 96Mi

  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

feed:
  image:
    repository: registry.lab.verysmart.house/watchedsky/feed
    tag: ""

  service:
    type: ClusterIP
    port: 3000

  resources:
    requests:
      cpu: 250m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  livenessProbe:
    httpGet:
      path: /livez
      port: http
  readinessProbe:
    httpGet:
      path: /readyz
      port: http

ingress:
  enabled: true
  className: contour-external
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: watchedsky.social
      paths:
        - path: /api
          pathType: Prefix
          service: core
          port: 8888
        - path: /
          pathType: Prefix
          service: frontend
          port: 3000
    - host: feed.watchedsky.social
      paths:
        - path: /
          pathType: Prefix
          service: feed
          port: 3000
  tls:
    - hosts:
        - watchedsky.social
        - feed.watchedsky.social
      secretName: watchedsky-social-tls

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetMemoryUtilizationPercentage: 90

secret:
  create: false
  # db_password: ""
  # bsky_id: ""
  # bsky_password: ""
