{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "watchedsky.fullname" . }}-feed
  labels:
    {{- include "watchedsky.labels" . | nindent 4 }}
stringData:
  .env: |
    FEEDGEN_DATABASE_PASSWORD={{ required ".Values.secret.db_password is required" .Values.secret.db_password }}
    FEEDGEN_HOSTNAME=feed.watchedsky.social
    FEEDGEN_LISTENHOST=0.0.0.0
    FEEDGEN_PORT=3000
    FEEDGEN_PUBLISHER_APP_PASSWORD={{ required ".Values.secret.feedPublisherAppPassword is required" .Values.secret.feedPublisherAppPassword }}
    FEEDGEN_PUBLISHER_DID=did:plc:hvjfuy2w6zqu6abmpkwcpulc
    FEEDGEN_PUBLISHER_HANDLE=watchedsky.social

{{- end -}}
