apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "watchedsky.fullname" . }}-frontend
  labels:
    {{- include "watchedsky.frontendLabels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "watchedsky.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "watchedsky.frontendLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "watchedsky.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}-frontend-server
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: {{ .Values.frontend.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.frontend.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.frontend.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
