apiVersion: v1
kind: Service
metadata:
  name: {{ include "watchedsky.fullname" . }}
  labels:
    {{- include "watchedsky.frontendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "watchedsky.frontendSelectorLabels" . | nindent 4 }}
