apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "watchedsky.fullname" . }}-publish-feed
  labels:
    {{- include "watchedsky.feedLabels" . | nindent 4 }}
spec:
  suspend: true
  template:
    metadata:
      labels:
        {{- include "watchedsky.feedLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-publish-feed
          image: "{{ .Values.feed.image.repository }}:{{ .Values.feed.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: Always
          command: ["/app/scripts/publishFeedGen.js"]
          resources:
            {{- toYaml .Values.feed.resources | nindent 12 }}
          volumeMounts:
            - name: secrets-env
              mountPath: /app/.env
              subPath: .env
              readOnly: true
      volumes:
        - name: secrets-env
          secret:
            secretName: {{ include "watchedsky.fullname" . }}-feed
      restartPolicy: Never
status: {}
