{{- if .Values.secret.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "watchedsky.fullname" . }}
  labels:
    {{- include "watchedsky.labels" . | nindent 4 }}
stringData:
  .env: |
    WATCHEDSKY_DB_PASSWORD={{ required ".Values.secret.db_password is required" .Values.secret.db_password }}
    WATCHEDSKY_ALERTS_BLUESKY_ID={{ required ".Values.secret.bsky_id is required" .Values.secret.bsky_id }}
    WATCHEDSKY_ALERTS_BLUESKY_APP_PASSWORD={{ required ".Values.secret.bsky_password is required" .Values.secret.bsky_password }}

{{- end -}}
